FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less man
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake libtool pkg-config bison flex libbz2-dev

ADD . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/bin/.libs
